name: Set Announcement URL for the given edition

description: Sets the `announcement_url` in version-info.json and version-info-ee.json. This powers the "What's New?" announcement.
on:
  workflow_dispatch:
    inputs:
      announcement-url:
        required: true
      edition:
        required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_S3_RELEASE_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_S3_RELEASE_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Prepare back-end environment
      uses: ./.github/actions/prepare-backend
      with:
        m2-cache-key: driver-${{ inputs.junit-name }}
    - name: Set the announcement URL
      run: clojure -X:build/build-announcement-url :edition ${{ github.event.inputs.edition }} :url ${{ github.event.inputs.announcement-url }}
      shell: bash
